version: '3'
services:
  dbpostgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=avapassword
      - POSTGRES_USER=avauser
      - POSTGRES_DB=avab
  frontend:
    build: ./availability
    ports:
      - '3000:3000'
  backend:
    build: ./AvabilityB
    ports:
      - '8080:8080'

 

